# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

before:
  hooks:
    - go mod tidy
    # refreshes the tailwind css
    - go generate ./...

builds:
  - id: go-ssb-room-linux-amd64
    env:
      # needed for sqlite
      - CGO_ENABLED=1
    main: ./cmd/server
    binary: go-ssb-room
    goos:
      - linux
    goarch:
      - amd64

  - id: go-ssb-room-insert-user-linux-amd64
    env:
      # needed for sqlite
      - CGO_ENABLED=1
    main: ./cmd/insert-user
    binary: go-ssb-room-insert-user
    goos:
      - linux
    goarch:
      - amd64

  - id: go-ssb-room-linux-arm64
    env:
      # needed for sqlite
      - CGO_ENABLED=1
      # cross-compilation
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    main: ./cmd/server
    binary: go-ssb-room
    goos:
      - linux
    goarch:
      - arm64

  - id: go-ssb-room-insert-user-linux-arm64
    env:
      # needed for sqlite
      - CGO_ENABLED=1
      # cross-compilation
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    main: ./cmd/insert-user
    binary: go-ssb-room-insert-user
    goos:
      - linux
    goarch:
      - arm64

  - id: go-ssb-room-linux-armhf
    env:
      # needed for sqlite
      - CGO_ENABLED=1
      # cross-compilation
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf--g++
    main: ./cmd/server
    binary: go-ssb-room
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
      - 7

  - id: go-ssb-room-insert-user-linux-armhf
    env:
      # needed for sqlite
      - CGO_ENABLED=1
      # cross-compilation
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf--g++
    main: ./cmd/insert-user
    binary: go-ssb-room-insert-user
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
      - 7

gomod:
  env:
    - GOPROXY=https://proxy.golang.org
    - GOSUMDB=sum.golang.org

# for .deb packages
# see: https://goreleaser.com/customization/nfpm/
nfpms:
 - id: go-ssb-room
   package_name: go-ssb-room
   vendor: Secure-Scuttlebutt Community
   maintainer: Go-SSB-Room NGI-Pointer Team <go-ssb-room@ssb-ngi-pointer.email>
   homepage: https://scuttlebutt.nz
   description: SSB Room v2 server, written in Go
   license: MIT
   formats:
     - deb
   suggests:
     - ngingx
     - certbot
   contents:
     - dst: /var/log/go-ssb-room
       type: dir

     - src: docs/files/example-systemd.service
       dst: /etc/systemd/system/go-ssb-room.service
       type: "config|noreplace"

     - src: docs/files/example-nginx.conf
       dst: /usr/share/go-ssb-room/nginx-example.conf

     # TODO: maybe (automatically) turn docs/README.md into a .txt with the links at the bottom?
     - src: README.md
       dst: /usr/share/go-ssb-room/README.md

     # TODO: add more docs we want?
   scripts:
     postinstall: docs/files/debian-postinstall.sh
     preremove: docs/files/debian-preremove.sh

archives:
  - id: go-ssb-room

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
